services:
  postgres:
    image: postgres:14
    restart: on-failure
    container_name: ${DOCKER_CONTAINER}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_SCHEMA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${HOST_PORT}:5432"
    volumes:
      - ./Scripts/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
      - ./Week 1 - Docker, SQL & Terraform/Data:/data/Week1
      - ./Week 3 - Data Warehouse/Data:/data/Week3
  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    # volumes:
    #   - pgadmin-data:/var/lib/pgadmin
  python:
    image: python:3.12.8
    container_name: python
    working_dir: /app  # Set the working directory inside the container
    command: python
    tty: true
